site_name: P치gina MkDocs

nav: 
    - Entornos: 
            - Tema 1: 
                - Ciclo de vida del Software: Tema_1_Ejercicios.md
                - Lenguajes de Programaci칩n: Tema1lenguajes.md
            - Tema 2:    
                - Herramientas de Desarrollo: Tema2_herramientas_Desarrollo.md
                - Entornos integrados de Desarrollo (IDE): Tema2ei.md
            - Tema 3-Control de Versiones: 
                - SistemaControlVersiones.md
            - Tema 4-Optimizaci칩n: 
                - T4-optimizacion.md
    - Lenguajes: 
        - Sobre la asignatura: 
            - Lenguajes de Marca: lenguajes.md
            - Creaccion de la p치gina: creaccion.md
        - Blogs varios:
            - One Piece: blog1.md
            
theme: readthedocs
